---
## Publish to NPM
name: Publish to NPM
# Start the job on all push
on:
  push:
    branches: [main]
    tags-ignore: ['**']
    paths-ignore: ['**/*.md', LICENSE, '**/*.gitignore', '.github/']
  pull_request: null
# Set the job
jobs:
  publish:
    # Name the job
    name: Publish
    # Set the job agent
    runs-on: [ubuntu-latest]
    # Grant job permissions
    permissions:
      contents: read
      packages: read
      statuses: write
      id-token: write
    # Load all steps
    steps:
      # Checkout the codebase
      - name: Checkout Code
        uses: actions/checkout@v4
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          check-latest: true
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      # Install all project dependencies for lint and tests
      - name: Run lint and tests...
        run: npm ci
      # Run lint, format and tests
      - name: Run lint & format
        run: npm run lint
      # Publish  codebase to NPM registry
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{secrets.NPM_TOKEN}}
          access: 'public'
          tag: 'latest'
          dry-run: false
          registry: 'https://registry.npmjs.org'

      - if: ${{ steps.publish.outputs.type }}
        run: echo "Published ${{ steps.publish.outputs.type }} ${{ steps.publish.outputs.name }}@${{ steps.publish.outputs.version }}"

        # ENV
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
